env: "dev"
storage_path: "/home/overlord/tmpfork/etc"
logfile_path: "/home/overlord/"
auth_password: "mypassword12345"
http_server:
  address: ":8080"
udp_server:
  address: ":8081"
bandwidth_tracking:
  collection_interval: "60s"
  storage_path: "bandwidth"